# Generated by Django 6.0.5 on 2026-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_add_admin_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
