# Generated by Django 6.0.5 on 2026-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_adminauditlog_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_points_per_dollar', models.IntegerField(default=10)),
                ('loyalty_point_value_usd', models.DecimalField(decimal_places=4, default=0.01, max_digits=5)),
                ('welcome_bonus_points', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
