# Generated by Django 6.0.5 on 2026-05-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='loyalty_points_ratio',
            field=models.IntegerField(default=100, help_text='Amount in Rupees required to earn 1 loyalty point. Set to 0 to disable.'),
        ),
    ]
