# Generated by Django 6.0.5 on 2026-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_loyalty_points_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
