# Generated by Django 6.0.5 on 2026-05-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_menuitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/banners/'),
        ),
    ]
