# Generated by Django 6.0.5 on 2026-07-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_force_closed',
            field=models.BooleanField(default=False, help_text='Super-Admin master override to force close the entire brand'),
        ),
    ]
