# Generated by Django 6.0.5 on 2026-07-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_update_operating_hours_247'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMenuItemAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_availabilities', to='restaurants.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availabilities', to='restaurants.menuitem')),
            ],
            options={
                'verbose_name_plural': 'Branch Menu Item Availabilities',
                'unique_together': {('branch', 'menu_item')},
            },
        ),
    ]
