# Generated by Django 6.0.5 on 2026-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurantreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_earn_rate_pkr', models.IntegerField(default=100, help_text='PKR spent to earn 1 loyalty point (e.g. 100 PKR = 1 pt)')),
                ('loyalty_point_value_pkr', models.IntegerField(default=1, help_text='PKR discount value per 1 loyalty point (e.g. 1 pt = 1 PKR)')),
                ('welcome_bonus_points', models.IntegerField(default=50, help_text='Loyalty points rewarded on new user registration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
