# Generated by Django 6.0.5 on 2026-07-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_platformsettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchrider',
            unique_together={('branch', 'phone')},
        ),
    ]
