# Generated by Django 6.0.5 on 2026-07-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_branchrider_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_dine_in_enabled',
            field=models.BooleanField(default=True, help_text='Enable Dine-In orders for this branch.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_dine_in_enabled',
            field=models.BooleanField(default=True, help_text='Enable Dine-In orders for this restaurant.'),
        ),
    ]
