"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
from django.core.exceptions import ImproperlyConfigured
_secret_key = config('SECRET_KEY', default='')
if not _secret_key:
    if str(config('DEBUG', default=False)).strip().lower() in ('true', '1', 't', 'y', 'yes'):
        import secrets
        _secret_key = secrets.token_hex(50)
        import warnings
        warnings.warn("SECRET_KEY not set — using random key for dev only!", stacklevel=2)
    else:
        raise ImproperlyConfigured("SECRET_KEY environment variable must be set in production!")
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(config('DEBUG', default=False)).strip().lower() in ('true', '1', 't', 'y', 'yes')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')

if not DEBUG and ALLOWED_HOSTS == ['*']:
    import warnings
    warnings.warn(
        "SECURITY WARNING: ALLOWED_HOSTS is set to '*' in production! "
        "Set it to your actual domain in environment variables.",
        stacklevel=2
    )

# Application definition

_CLOUDINARY_ACTIVE = bool(
    config('CLOUDINARY_CLOUD_NAME', default='') and
    config('CLOUDINARY_API_KEY', default='') and
    config('CLOUDINARY_API_SECRET', default='')
)

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + (['cloudinary_storage'] if _CLOUDINARY_ACTIVE else []) + [
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'import_export',
] + (['cloudinary'] if _CLOUDINARY_ACTIVE else []) + [
    # Local apps
    'config',
    'restaurants',
    'orders',
    'users',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be placed at the beginning
    'config.middleware.MethodOverrideMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os
from urllib.parse import urlparse

DATABASE_URL = os.environ.get('DATABASE_URL')
DB_HOST = os.environ.get('DB_HOST')
DB_PORT = os.environ.get('DB_PORT', '6543')
DB_NAME = os.environ.get('DB_NAME', 'postgres')
DB_USER = os.environ.get('DB_USER')
DB_PASSWORD = os.environ.get('DB_PASSWORD')

# Parse DATABASE_URL if available
if DATABASE_URL:
    try:
        parsed = urlparse(DATABASE_URL)
        DB_HOST = parsed.hostname or DB_HOST
        DB_PORT = str(parsed.port) if parsed.port else DB_PORT
        DB_NAME = parsed.path.lstrip('/') if parsed.path else DB_NAME
        DB_USER = parsed.username or DB_USER
        DB_PASSWORD = parsed.password or DB_PASSWORD
    except Exception:
        pass

# BUG-18 FIX: Supabase tenant suffix from environment variable — not hardcoded
SUPABASE_TENANT_SUFFIX = os.environ.get('SUPABASE_TENANT_SUFFIX', '')
if DB_USER and SUPABASE_TENANT_SUFFIX and '.' not in DB_USER:
    DB_USER = f"{DB_USER}.{SUPABASE_TENANT_SUFFIX}"

if DB_HOST and DB_USER and DB_PASSWORD:
    # Production: Supabase PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
        }
    }
else:
    # Local development: SQLite fallback
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
WHITENOISE_MANIFEST_STRICT = False

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Media Files (Uploads)
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')
BACKEND_URL = config('BACKEND_URL', default='https://restaurant-app-web.onrender.com')

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='foodsphere.support@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='FoodSphere <foodsphere.support@gmail.com>')

if _CLOUDINARY_ACTIVE:
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True
    )
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        }
    }
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        }
    }

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '500/hour',
        'user': '2000/hour',
        'order_create': '200/hour',
    },
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardResultsPagination',
    'PAGE_SIZE': 20,
}

# Simple JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=6),    # FIX 1D: Extended from 60min → 6h to prevent
                                                    # 3rd-4th launch 401 from token rotation race.
                                                    # Frequent short-lived tokens + ROTATE_REFRESH_TOKENS=True
                                                    # caused blacklisted token reuse on rapid relaunches.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),   # 30 days comfortable UX
    'ROTATE_REFRESH_TOKENS': True,      # Rotate refresh tokens
    'BLACKLIST_AFTER_ROTATION': True,   # Blacklist rotated tokens
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# CORS Settings — BUG-21 FIX
# Allow all origins for API usage (JWT handles security, not CORS)
CORS_ALLOW_ALL_ORIGINS = str(os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False')).lower() in ('true', '1', 'yes')

# Explicit origins as fallback when CORS_ALLOW_ALL_ORIGINS=False
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:8081,http://localhost:19006,http://localhost:19000,https://foodsphere-admin.netlify.app,https://foodsphere-app.pages.dev'
).split(',')

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.pages\.dev$",
    r"^https://.*\.netlify\.app$",
    r"^https://.*\.expo\.dev$",
    r"^exp://.*$",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-http-method-override',
]

# OWASP 2025 Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Secure Cookies in Production
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Jazzmin Admin Panel Configuration
JAZZMIN_SETTINGS = {
    # Window/Tab Title
    "site_title": "FoodSphere HQ",
    "site_header": "FoodSphere",
    "site_brand": "FoodSphere",
    "welcome_sign": "Welcome back, Commander 🚀",
    "copyright": "© 2026 FoodSphere Ltd. All rights reserved.",

    # Logo — uses site_brand text if no logo file exists
    "site_logo": None,
    "login_logo": None,
    "site_logo_classes": "img-circle",

    # Top-bar search models
    "search_model": ["users.User", "restaurants.Restaurant", "orders.Order"],

    # User avatar
    "user_avatar": None,

    # Top menu links
    "topmenu_links": [
        {"name": "🏠 Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "🌐 Live App", "url": "https://restaurant-app-web.onrender.com/", "new_window": True},
        {"name": "📊 API Docs", "url": "/api/", "new_window": True},
    ],

    # Sidebar config
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Ordering of sidebar sections
    "order_with_respect_to": [
        "restaurants",
        "orders",
        "payments",
        "users",
        "auth",
    ],

    # Custom sidebar links (appear at bottom)
    "custom_links": {
        "orders": [{
            "name": "📊 Platform Analytics",
            "url": "/admin/analytics/",
            "icon": "fas fa-chart-line",
            "permissions": ["auth.view_user"],
        }],
    },

    # Premium FontAwesome 5 Icons
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-secret",
        "auth.Group": "fas fa-user-friends",
        "users.user": "fas fa-user-astronaut",
        "users.loyaltytransaction": "fas fa-gem",
        "restaurants.restaurant": "fas fa-store-alt",
        "restaurants.menucategory": "fas fa-layer-group",
        "restaurants.menuitem": "fas fa-utensils",
        "orders.order": "fas fa-shopping-bag",
        "orders.orderitem": "fas fa-box-open",
        "payments.payment": "fas fa-credit-card",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",

    # UI Behavior
    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # Custom CSS/JS injection (CRITICAL for premium look)
    "custom_css": "css/admin_custom.css",
    "custom_js": None,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

# ═══════════════════════════════════════
# LOGGING CONFIGURATION
# ═══════════════════════════════════════
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} — {message}',
            'style': '{',
        },
        'json': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'orders': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'payments': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'config': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# ─────────────────────────────────────────────────────────
# PAYMENT GATEWAYS — COD + PayFast only (Stripe removed)
# ─────────────────────────────────────────────────────────

# PayFast — Local Pakistani payment gateway
# Sandbox default credentials (replace with live keys in Render env vars)
PAYFAST_MERCHANT_ID = config('PAYFAST_MERCHANT_ID', default='10000100')      # Sandbox merchant ID
PAYFAST_MERCHANT_KEY = config('PAYFAST_MERCHANT_KEY', default='46f0z58cltpa2') # Sandbox merchant key
PAYFAST_PASSPHRASE = config('PAYFAST_PASSPHRASE', default='jt776ha7zb0b7')   # Sandbox passphrase
PAYFAST_IS_SANDBOX = config('PAYFAST_IS_SANDBOX', cast=bool, default=True)
PAYFAST_HOST = 'sandbox.payfast.co.za' if PAYFAST_IS_SANDBOX else 'www.payfast.co.za'

# ─────────────────────────────────────────────────────────
# FIREBASE — Push Notifications (Client provides their own)
# Set FCM_SERVICE_ACCOUNT_JSON in Render environment variables
# Download from: Firebase Console → Project Settings → Service Accounts
# ─────────────────────────────────────────────────────────
FCM_SERVICE_ACCOUNT_JSON = os.environ.get('FCM_SERVICE_ACCOUNT_JSON', '')

# RIDER WHATSAPP DISPATCH NUMBER
RIDER_WHATSAPP = os.environ.get('RIDER_WHATSAPP_NUMBER', '923000000000')

# Sentry Monitoring integration
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.05 if not DEBUG else 0.0,  # Production mein 5% sampling
        send_default_pii=False,
        environment='development' if DEBUG else 'production',
        release=os.environ.get('RENDER_GIT_COMMIT', 'unknown'),
    )

# Security and HSTS Config (SEC-1)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Cache & Session Settings (Production Redis) ──────────────────────────
REDIS_URL = config('REDIS_URL', default=None)
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 20,
                    "retry_on_timeout": True
                }
            }
        }
    }
    # Store user sessions in Redis instead of the database for 10x faster lookups
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Safe fallback for local development (no Redis required)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }


