# Generated by Django 6.0.5 on 2026-07-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_method_alter_orderitem_quantity'),
        ('restaurants', '0006_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Auto-assigned branch based on customer delivery area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.branch'),
        ),
    ]
