# Generated by Django 6.0.5 on 2026-07-26 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_branch'),
        ('restaurants', '0008_update_operating_hours_247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason recorded if order is cancelled.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BranchCashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_orders_count', models.IntegerField(default=0)),
                ('total_cod_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cod_handed_over', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discrepancy_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_verified_by_admin', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='restaurants.branch')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cash_registers', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cash_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Cash Register',
                'verbose_name_plural': 'Branch Cash Registers',
                'ordering': ['-date'],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
