# Generated by Django 6.0.5 on 2026-07-26 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_cancellation_reason_order_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Secure token for guest order tracking. Returned at order creation and stored client-side.'),
        ),
    ]
