# Generated by Django 6.0.5 on 2026-07-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_tracking_token'),
        ('restaurants', '0010_branch_delivery_radius_km_branch_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, help_text='Assigned rider for delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.branchrider'),
        ),
    ]
