# Generated by Django 6.0.5 on 2026-07-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Tenant and branch scoped human-readable order ID (e.g., TS-LC-1001).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=20),
        ),
    ]
