# Generated by Django 6.0.5 on 2026-07-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_populate_display_order_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('TAKEAWAY', 'Takeaway'), ('DINE_IN', 'Dine-In')], db_index=True, default='DELIVERY', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Table number for Dine-In orders.', max_length=30, null=True),
        ),
    ]
