# Generated by Django 6.0.5 on 2026-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
