# Generated by Django 6.0.5 on 2026-07-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_coupon_times_used'),
        ('restaurants', '0013_alter_branchrider_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurants.branch'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurants.restaurant'),
        ),
    ]
