# Generated by Django 6.0.5 on 2026-07-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_coupon_branch_alter_coupon_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_dine_in_only',
            field=models.BooleanField(default=False, help_text='Exclusively available for Dine-In orders.'),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='is_dine_in_only',
            field=models.BooleanField(default=False, help_text='Exclusively available for Dine-In mode.'),
        ),
    ]
