# Generated by Django 6.0.5 on 2026-08-17 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_order_type_order_table_number'),
        ('promotions', '0005_alter_coupon_valid_from_alter_coupon_valid_to'),
        ('restaurants', '0014_branch_is_dine_in_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashdeal',
            name='is_dine_in_only',
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='active_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_deals', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='flash_deals', to='restaurants.menucategory'),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='daily_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='daily_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='item_scope_type',
            field=models.CharField(choices=[('ENTIRE_MENU', 'Entire Store Menu'), ('CATEGORY', 'Specific Categories'), ('SPECIFIC_ITEMS', 'Specific Menu Items')], default='ENTIRE_MENU', max_length=20),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='min_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='order_mode',
            field=models.CharField(choices=[('ALL', 'All Order Modes'), ('DELIVERY', 'Delivery & Takeaway Only'), ('DINE_IN', 'Dine-In Exclusive')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority overrides overlapping deals'),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='redemption_reset_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily Reset'), ('LIFETIME', 'Lifetime Cap')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='timezone',
            field=models.CharField(default='Asia/Karachi', max_length=50),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='timing_type',
            field=models.CharField(choices=[('ONE_TIME', 'One-Time Window'), ('RECURRING_DAILY', 'Recurring Daily Schedule')], default='ONE_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='deal_type',
            field=models.CharField(choices=[('percentage', '% Off'), ('flat', 'Flat Rs. Off'), ('bogo', 'Buy 1 Get 1 Free'), ('combo', 'Combo Bundle')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='max_orders',
            field=models.IntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='menu_items',
            field=models.ManyToManyField(blank=True, related_name='flash_deals', to='restaurants.menuitem'),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='orders_used',
            field=models.IntegerField(default=0, help_text='Legacy counter, computed dynamically from redemptions'),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_deals', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='FlashDealRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('flash_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promotions.flashdeal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_redemptions', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['flash_deal', 'redeemed_at'], name='promotions__flash_d_aef186_idx')],
            },
        ),
    ]
