# Generated by Django 6.0.5 on 2026-09-13 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_options_order_order_rest_created_idx_and_more'),
        ('promotions', '0006_remove_flashdeal_is_dine_in_only_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='coupon_user_usage_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'order'], name='coupon_order_usage_idx'),
        ),
    ]
