# Generated by Django 6.0.5 on 2026-05-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at_alter_order_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('order', 'method')},
        ),
    ]
